# Site settings
title: "CWC Architectural Millwork"
description: "Custom millwork solutions that transform spaces with precision craftsmanship and innovative design."
url: "" # Update with your domain when deployed
baseurl: "" # Update if deploying to a subdirectory

# Contact information
phone: "1-866-525-6868"
email: "info@cwcmillwork.ca"
address: "18 - 34378 Manufacturers Way, Abbotsford, BC V2S 7M1"

# Company details
company_name: "CWC Architectural Millwork 2007 Inc."
year_established: "2007"

# Key Personnel
personnel:
  - name: "Ted Bostrom"
    title: "President & General Manager"
    email: "ted@cwcmillwork.ca"
  - name: "Pauline Bostrom"
    title: "Comptroller"
    email: "pauline@cwcmillwork.ca"
  - name: "John Beauchamp"
    title: "Production Manager"
    email: "john@cwcmillwork.ca"
  - name: "Karl Reisinger"
    title: "Project Manager"
    email: "karl@cwcmillwork.ca"
  - name: "Cole Bostrom"
    title: "Estimating"
    email: "cole@cwcmillwork.ca"

# Social media (add your handles)
# facebook: "cwcmillwork"
# instagram: "cwcmillwork"
# linkedin: "company/cwc-millwork"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio-item"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: "CWC Architectural Millwork"
twitter:
  username: "cwcmillwork" # Update with actual handle
logo: "/assets/images/logo.gif" 